name: ⚙️ Build with Parameters

on:
  workflow_dispatch:
    inputs:
      id:
        description: 'Run identifier'
        required: false
      startUrl:
        description: 'URL against which the tests are run'
        default: 'mercury.sandbox.starofservice.com'
        required: true
      marker:
        default: ''

jobs:
  conspector:
    name: 🔎 CONSPECTOR
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.event.inputs.id }}
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo run identifier ${{ inputs.id }}
      - name: 📦 Set env variable
        run: |
          if [ "${{ github.event.inputs.startUrl }}" == "mercury.starofservice.com" ]; then
            env="PROD"
          else
            env="DEV"
          fi
          jwt_key_name="JWT_KEY_${env}"
          echo "JWT_KEY=$jwt_key_name" >> $GITHUB_ENV
      - name: 🛎 Checkout branch
        uses: actions/checkout@v3
      - name: ⚙️ Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: ⚙️ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: 🧪 Run tests
        id: pytest
        uses: dariocurr/pytest-summary@main
        with:
          show: "fail, pass"
          options: --start_url '${{ github.event.inputs.startUrl }}' -m '${{ github.event.inputs.marker }}' --jwt_key '${{ secrets[env.JWT_KEY] }}'

      - name: 📦 Define vars for Slack
        if: always()
        run: |
          if [[ "${{ steps.pytest.conclusion }}" == "failure" ]]
          then
            echo "SLACK_COLOR=f71414" >> $GITHUB_ENV
          else
            echo "SLACK_COLOR=28a745" >> $GITHUB_ENV
          fi
      - name: 📩 Post message to Slack
        if: always()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C2V09T50R'
          payload: |
            {
              "text": "",
              "dispatch_action": true,
              "attachments": [
                {
                  "color": "${{ env.SLACK_COLOR }}",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "🧪 Run *<${{ env.BUILD_URL }}|#${{ github.run_number }}>* finished on `${{ github.ref_name }}` with the status: *${{ steps.pytest.conclusion }}*"
                      }
                    },
                    {
                      "type": "context",
                      "elements": [
                        {
                          "type": "mrkdwn",
                          "text": "🤖️ Triggered by ${{ github.actor }}"
                        }
                      ]
                    },
                    {
                      "type": "actions",
                      "elements": [
                        {
                          "type": "button",
                          "text": {
                            "type": "plain_text",
                            "text": "BUILD PAGE",
                            "emoji": true
                          },
                          "url": "${{ env.BUILD_URL }}"
                        }
                      ]
                    }
                  ]
                }
              ]
            }

env:
    SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    BUILD_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"